## Numpy Arraya and Baiscs
learn about numpy

In [ ]:
import numpy as np


### array from list


In [20]:
arr_1d =np.array([1,3,6,8,10])
print("1D array: " ,arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array: \n", arr_2d)

1D array:  [ 1  3  6  8 10]
2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### zeros array

In [21]:
zeros=np.zeros((4,5))
print("Zeros array: \n", zeros)


ones=np.ones((3,4))
print("Ones array: \n", ones)

Zeros array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### vector , matrix and tensor

In [22]:
tensor=np.array([[[3,4,5],[6,7,8]],[[9,10,11],[12,13,14]]])
print("Tensor array: \n", tensor)

vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix: \n", matrix)

Tensor array: 
 [[[ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]]]
Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### array properties

In [23]:
shape_arr = np.array([[1,2,3,4],[5,6,7,8]])
print("Shape of array: ", shape_arr.shape)
dtype_arr = np.array([1,2,3,4], dtype=np.float64)
print("Data type of array: ", dtype_arr.dtype)
size_arr = np.array([[1,2,3],[4,5,6]])
print("Size of array: ", size_arr.size)
ndim_arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Number of dimensions: ", ndim_arr.ndim)
itemsize_arr = np.array([1,2,3,4], dtype=np.int32)
print("Item size in bytes: ", itemsize_arr.itemsize)

Shape of array:  (2, 4)
Data type of array:  float64
Size of array:  6
Number of dimensions:  3
Item size in bytes:  4


### reshape an array

In [30]:
arr=np.arange(12)
reshaped_arr=arr.reshape((3,4))
print("Original array: ", arr)
print("Reshaped array (3x4): \n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print("Flattened array: ", flattened_arr)

# ravel is similar to flatten but returns a view instead of a copy
raveled_arr = reshaped_arr.ravel()
print("Raveled array: ", raveled_arr)


transposed_arr = reshaped_arr.T
print("Transposed array: \n", transposed_arr)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4): 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
