### Numpy Array Operations

In [3]:
import numpy as np

### filter

In [6]:
unsorted=np.array([1,2,3,19,5,6,7,8,9,10])
print("sorted array",np.sort(unsorted))

print(unsorted[unsorted%2!=0])
print(unsorted[unsorted%2==0])

sorted array [ 1  2  3  5  6  7  8  9 10 19]
[ 1  3 19  5  7  9]
[ 2  6  8 10]


In [8]:
mask=unsorted>4
mask1=unsorted<4
print("mask numbers",unsorted[mask])
print("mask1 numbers",unsorted[mask1])

mask numbers [19  5  6  7  8  9 10]
mask1 numbers [1 2 3]


### fancy indexing and where clause

In [12]:
unsorted=np.array([1,2,3,19,5,6,7,8,9,10])
indices=[0,3,5,6,8]
print(unsorted[indices])

nums=np.array([1,2,3,4,5,6,7,8,9,10])
where_nums=np.where(nums >5)
print(where_nums)
print(nums[where_nums])

print(np.where(nums>5 ,nums*2,nums))

[ 1 19  6  7  9]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]


### Adding And Removing Data

In [24]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(np.concatenate((arr1,arr2)))


original=np.array([1,2,3])
new=np.array([4,5,6])
print(np.vstack((original,new)))
new_col=np.array([1,3,4])
print(np.hstack((original,new_col)))


num=np.array([1,6,8,9])
print("deleted num :",np.delete(num,3))
print("deleted num :",np.delete(num,1))



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 1 3 4]
deleted num : [1 6 8]
deleted num : [1 8 9]
